### ISSUE TITLE
Test fails if you put space after 'is' and does not work with 'James' as asked.

### ISSUE THREAD

**Issue by Rhpozzo** [4GeeksAcademy/react-tutorial-exercises#24]
https://github.com/4GeeksAcademy/react-exercises/blob/7c7c73a647e86815f32eb9d7e29c620563d34006/exercises/01.2-hello-jsx/tests.js#L12

Does not pass:
<img width="1113" alt="Screen Shot 2019-11-09 at 11 30 26 AM" src="https://user-images.githubusercontent.com/32078327/68531842-c63e6b80-02e4-11ea-84af-60828cd3bc04.png">

Passes:
<img width="1125" alt="Screen Shot 2019-11-09 at 11 32 48 AM" src="https://user-images.githubusercontent.com/32078327/68531848-d0f90080-02e4-11ea-8029-2df2d398aa92.png">

**Comment by alesanchezr** [comment]
Yes, this issue drives me crazy.. I still don't know how to fix it.

Basically the prettier and the test are fighting each other. The prettier ads the space and the test ignores it.

**Comment by tommygonzaleza** [comment]
I fixed it before, this is the PR: https://github.com/4GeeksAcademy/react-tutorial-exercises/pull/49
