### ISSUE TITLE
Cover the following topics with exercises

### ISSUE THREAD

**Issue by alesanchezr** [4GeeksAcademy/react-tutorial-exercises#5]
Hey @teachers there are already 17 exercises on the react.js exercises.

The current exercises are covering the following topics:

- [x] JSX Intruction.
- [x] Using variables in JSX.
- [x] ReactDOM.render().
- [x] JSX html arrays and keys.
- [x] Mapping arrays with JSX.
    - [ ] Mapping inline on the return statement.
- [x] Creating components.
- [x] Conditional rendering.
    - [ ] Conditional rendering inline (ternary) on the returning statment.
- [x] Component properties and validations.
    - [x] Proptypes

The following topics are scheduled for version 0.2
- [ ] Class components.
- [ ] Component State.
- [ ] State vs Props.
- [ ] Live cycle methods
    - [ ] constructor
    - [ ] componentDidMount
    - [ ] render
    - [ ] getDerivatedStateFromProps

**Comment by alesanchezr** [comment]
I don't know if I should be covering class components or just ignore that and explain hooks instead. What do you think @nachovz?

**Comment by jferragut** [comment]
@alesanchezr @nachovz I don't think that hooks are meant to be a replacement for classes. Even the React docs on hooks say that. [Link to source](https://reactjs.org/docs/hooks-intro.html#no-breaking-changes) 

Maybe cover both? Hooks have a place when we want to pull things into functional components, but I have a feeling classes will still be the de facto standard for views. 

Hope you guys don't mind that I interjected. I am subscribed to updates on this thread.

**Comment by nachovz** [comment]
@jferragut how dare you? XD Kidding.

I stand with @jferragut, even though Hooks are very interesting they're not here to replace classes: 

> **There are no plans to remove classes from React**

We always have to keep in mind that the students will rely on internet tutorials and there are plenty of those talking and explaining with class components.

**Comment by jferragut** [comment]
@nachovz glad that you've graced me with your permission! hahaha

**Comment by jferragut** [comment]
@alesanchezr I understand completely! Sounds good.
